# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 15:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('likes', models.IntegerField(default=0)),
                ('picture', models.ImageField(blank=True, upload_to='character_images')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChaRate.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('genre', models.CharField(choices=[('sci', 'Sci-Fi'), ('action', 'Action'), ('horror', 'Horror'), ('comedy', 'Comedy'), ('romance', 'Romance'), ('other', 'Other')], default='other', max_length=20)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('genre', models.CharField(choices=[('sci', 'Sci-Fi'), ('action', 'Action'), ('horror', 'Horror'), ('comedy', 'Comedy'), ('romance', 'Romance'), ('other', 'Other')], default='other', max_length=20)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'TV Shows',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommentCount', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChaRate.UserProfile'),
        ),
        migrations.AddField(
            model_name='character',
            name='movies',
            field=models.ManyToManyField(to='ChaRate.Movie'),
        ),
        migrations.AddField(
            model_name='character',
            name='tvshows',
            field=models.ManyToManyField(to='ChaRate.TV'),
        ),
    ]
