# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChaRate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
