# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChaRate', '0002_auto_20180322_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
