# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChaRate', '0006_userprofile_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='liked',
        ),
    ]
