# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChaRate', '0007_remove_userprofile_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='liked',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ChaRate.Character'),
        ),
    ]
