# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChaRate', '0006_auto_20180327_1710'),
        ('ChaRate', '0010_auto_20180327_1437'),
    ]

    operations = [
    ]
