# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChaRate', '0011_merge_20180327_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='liked',
        ),
        migrations.AddField(
            model_name='character',
            name='likedBy',
            field=models.ManyToManyField(to='ChaRate.Profile'),
        ),
    ]
